name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  OUTPUT_DIR: ${{github.workspace}}/output
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: 5.4
      
    - name: Install Dependencies
      run: sudo apt-get install libc6-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libgl-dev
      
    - name: Create Output Directory
      run: mkdir ${{env.OUTPUT_DIR}}
      
    - name: Checkout Submodules
      run: git submodule update --init --recursive
      
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
        -DLua_ROOT=.lua/ \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{env.OUTPUT_DIR}} \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{env.OUTPUT_DIR}} \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target procyon-lua
    
    - name: Cleanup
      run: rm ${{env.OUTPUT_DIR}}/genhexer
      
    - name: Copy Misc. Files
      run: |
        mkdir ${{env.OUTPUT_DIR}}/script && \
        cp lua/sample/main.lua ${{env.OUTPUT_DIR}}/script/main.lua && \
        cp lua/sample/util.lua ${{env.OUTPUT_DIR}}/script/util.lua && \
        cp lua/sample/sprites.png ${{env.OUTPUT_DIR}}/script/sprites.png && \
        cp lua/sample/CREDIT ${{env.OUTPUT_DIR}}/script/CREDIT && \
        cp lua/README.md ${{env.OUTPUT_DIR}}/README

    - name: Set-Executable
      run: chmod +x ${{env.OUTPUT_DIR}}/procyon-lua
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: linux-${{env.BUILD_TYPE}}
        path: ${{env.OUTPUT_DIR}}
