name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  OUTPUT_DIR: output
  LUA_DIR: lua
  LUA_VERSION: 5.4.3
  
jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        msystem: [MINGW32, MINGW64]
        build-type: [Debug, Release]
        include:
          - msystem: MINGW32
            arch: i686
          - msystem: MINGW64
            arch: x86_64
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.msystem}}
        install: >-
          make
          pkg-config
          gcc
          wget
          tar
          git
         
    - name: Install Additional Packages
      run: |
        pacman -S --noconfirm \
        mingw-w64-${{matrix.arch}}-cmake \
        mingw-w64-${{matrix.arch}}-gcc
    
    - name: Build Lua
      run: |
        mkdir ${{env.LUA_DIR}} && \
        wget https://www.lua.org/ftp/lua-${{env.LUA_VERSION}}.tar.gz -O lua.tar.gz && \
        tar -C ${{env.LUA_DIR}} -xvzf lua.tar.gz && \
        make -C ${{env.LUA_DIR}}/lua-${{env.LUA_VERSION}} -j mingw MYCFLAGS="-O3"
        
    - uses: actions/checkout@v2
    - name: Checkout Submodules
      run: git submodule update --init --recursive
      
    - name: Create Output Directory
      run: mkdir $(realpath ${{env.OUTPUT_DIR}})
      
    - name: Configure CMake
      run: |
        cmake \
        -B build \
        -G "MSYS Makefiles" \
        -DLua_ROOT="${{env.LUA_DIR}}/lua-${{env.LUA_VERSION}}/src"
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$(realpath ${{env.OUTPUT_DIR}}) \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$(realpath ${{env.OUTPUT_DIR}}) \
        -DCMAKE_BUILD_TYPE=${{matrix.build-type}}
        
    - name: Build
      run: cmake --build build --target procyon-lua
    
    - name: Clean Up
      run: rm ${{env.OUTPUT_DIR}}/genhexer
    
    - name: Strip Binaries
      run: strip --strip-unneeded ${{env.OUTPUT_DIR}}/*
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: windows-${{matrix.arch}}-${{matrix.build-type}}
        path: ${{env.OUTPUT_DIR}}

